name: Build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm run ci-build
      - run: docker-compose -f ./docker/docker-compose.yml up -d 
      - run: pnpm test:int