name: Build and test
on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm run ci-build
      - run: docker-compose -f ./docker/docker-compose.yml up -d
      - run: sleep 10
      - run: pnpm test:int
  layer_validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: layer
    steps:
      - uses: actions/checkout@v3
      - run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}